#!/bin/bash

echo "-------------------------------- DELETE AKAUN SSH --------------------------------"

echo "                           ALL SUPPORTED BY GollumVPN                            "
                           
read -p "Enter username to be removed: " username

                userdel $username
                echo ""
                echo -e "\e[1;32mAkaun [$username] berjaya dihapuskan\e[0m"
                exit 1
fi

cd ~/
rm -f /root/IP
