#!/bin/bash


MYIP=$(wget -qO- ipv4.icanhazip.com)
echo "------------------------------- MEMBUAT AKAUN SSH & OVPN -------------------------------"

if [[ $vps = "soned" ]]; then
	echo "                            Support GollumVPN                            "
	echo "                            Script by SYAHZ86      "
else
	echo "                                                 "
	echo "                "
fi

	echo "                   "
        echo ""

        read -p "Enter username: " username
        read -p "Enter password: " pass
        read -p "Enter expiry date (YYYY-MM-DD): " expdate
	
	echo "$username:$pass" | chpasswd
	usermod -e $expdate $username


	echo ""
	echo "-----------------------------------"
	echo "Data Login:"
	echo "-----------------------------------"
	echo "Host/IP: $MYIP"
	echo "Dropbear Port: 443, 110, 109"
	echo "OpenSSH Port: 22, 143"
	echo "Squid Proxy: 8080, 3128"
	#echo "OpenVPN Config: http://$MYIP:81/client.ovpn"
	echo "Username: $username"
	echo "Password: $pass"
	echo "Expired : $expdate"
	echo "-----------------------------------"
fi

cd ~/
rm -f /root/IP
