#!/bin/bash

if [[ $USER != 'root' ]]; then
	echo "Maaf, Anda harus menjalankan ini sebagai root"
	exit
fi

MYIP=$(wget -qO- ipv4.icanhazip.com)

echo "---------------------------- RENEW AKAUN SSH ----------------------------"

if [[ $vps = "soned" ]]; then
	echo "                Support Us at GollumVPN    "
	
else
	echo "                  DEVELOPED BY SYAHZ86     "
fi

	echo "                    SCRIPT BY SYAHZ86      "
echo ""

        read -p "Enter username to renew: " username
        read -p "Enter expiry date (YYYY-MM-DD): " expdate

	echo "New expiration date for $uname: $expdate...";
	usermod -e $expdate $username
	
	echo ""
	echo "-----------------------------------"
	echo "Data Login:"
	echo "-----------------------------------"
	echo "Host/IP: $MYIP"
	echo "Dropbear Port: 443, 110, 109"
	echo "OpenSSH Port: 22, 143"
	echo "Squid Proxy: 8080, 3128"
	#echo "OpenVPN Config: http://$MYIP:81/client.ovpn"
	echo "Username: $username"
	echo "Expired : $expdate"
	echo "-----------------------------------"
fi

cd ~/
rm -f /root/IP
